{
    "check.redacted": "<REDACTED>",
    "check.redacted.all": "<ALL REDACTED>",
    "core.help.alias": "Alias: ",
    "core.help.none": "(This module has no help information)",
    "core.help.options": "Options: ",
    "error": "An error occurred: ",
    "error.loader.load.failed": "The following error(s) occurred during module loading and module(s) with error was/were not loaded: ${err_msg}",
    "error.loader.load.success": "Loaded all modules successfully.",
    "error.message.chain.empty": "The bot attempted to send an empty message chain. Please get in touch with the developers to solve this issue.",
    "error.message.chain.invalid": "The bot attempted to send an invalid message chain. Please get in touch with the developers to solve this issue.",
    "error.message.chain.plain.empty": "The bot attempted to send an empty text message. Please get in touch with the developers to solve this issue.",
    "error.message.chain.unsafe": "The message contains insecure content and has been blocked. Please get in touch with the developers to solve this issue.",
    "error.message.limited": "Failed to send message. The message might be blocked. Please try again later.",
    "error.message.paused": "Group message delivering was blocked by the server. Group message delivering is suspended. Resume with ${prefix}resume command.",
    "error.module.helpdoc.invalid": "${module} provided an invalid help message. Please get in touch with the developers to solve this issue.",
    "error.module.unbound": "Module ${module} isn't bound with any commands and doesn't have a description. Please get in touch with the developers to solve this issue.",
    "error.range.notnumber": "发生错误：无效的数字区间。",
    "error.range.invalid": "发生错误：最小值不能大于最大值。",
    "error.prompt": "An error occurred: ${error_msg}\nReport this issue: ",
    "error.prompt.noreport": "An error occurred while executing the command:\n${err_msg}\nThis error is not caused by the bot (e.g. the API request went wrong) and thus should not be reported to developers.",
    "error.prompt.report": "An error occurred while executing the command. Please report the following to developers:\n${err_msg}\nReport this issue: ",
    "error.request.api.timeout": "API request timeout.",
    "example": "Hello world!",
    "i18n.prompt.fallback.failed": "(If you can see this, we've messed something up!\nPlease send the problem back to\n${url}\nso it can be fixed in time.)",
    "language": "English",
    "message.reply.prompt": "(Please reply to this message using the specified words)",
    "message.wait.confirm.prompt.type1": "(send \"Yes\" or other matching words to confirm)",
    "message.wait.confirm.prompt.type2": "(send matching words to confirm)",
    "no": "No",
    "none": "None",
    "parser.admin.module.permission.denied": "Commands under the \"${module}\" module can only be used by the admins of the group. Please contact the admins to execute the command.",
    "parser.admin.submodule.permission.denied": "This command can only be used by the admins of the group. Please contact the admins to execute the command.",
    "parser.command.format.invalid": "Syntax error.\nUse \"${prefix}help ${module}\" for help.",
    "parser.command.running.prompt": "There are currently commands running. Please try again later.",
    "parser.command.running.prompt2": "The previous command is being executed.",
    "parser.module.desc": "Description:\n${desc}",
    "parser.module.disabled.prompt": "\"${module}\" module is not enabled, please send ${prefix}enable ${module} to enable the module.",
    "parser.sudo.permission.denied": "You are not a superuser and cannot use the sudo command.",
    "parser.superuser.permission.denied": "You do not have permission to use this command.",
    "success": "Success.",
    "tos.reason": "Reason: ",
    "tos.reason.abuse": "Too many command usages within a period of time.",
    "tos.reason.bypass": "Ignoring temporary ban warning.",
    "tos.reason.cooldown": "Too many usages of the same command within a period of time.",
    "tos.tempbanned": "Note:\nWe have temporarily banned you because your action triggered a warning.\n${ban_time} seconds remaining until unban.",
    "tos.tempbanned.warning": "Note:\nAlthough a temporary block was triggered, using commands still may cause you to be warned again.\n${ban_time} seconds remaining until unban.",
    "tos.warning": "Warning:\nYou have violated our Code of Conduct according to our Terms of Service.",
    "tos.warning.appeal": "For objections, go to ${issue_url} and create an issue.",
    "tos.warning.count": "You have received ${current_warns} warnings. Your account will be blacklisted if you receive more than 5 warnings.",
    "tos.warning.last": "This is your last warning.",
    "yes": "Yes"
}